### PR TITLE
add save-all

### PR DESCRIPTION
**Pull request by pienjo**
Add a command to save all open and modified files.

### CODE REVIEW

**Comment by thomaswilburn** [comment]
This looks fine, but if we're going to support the asynchronous command style (with the callback at the end), should this code only call `c()` after all tabs have saved successfully?

**Comment by pienjo** [comment]
It probably should. I'll try to address that - the last time I did anything with javascript was somewhere around 1997; I'm stll trying to get my head around promises :)

**Comment by thomaswilburn** [comment]
No worries. There's a module at `util/manos` that is our version of Caolan's `async` library, and that will be useful when it comes to handling these things collectively. You may look at the code for exiting the application, which has a similar flow (all tabs must be saved/discarded before Caret actually quits).

**Comment by pienjo** [comment]
Right. I think I've got it now :)

**Comment by thomaswilburn** [comment]
Looks good, thanks.

**Comment by pienjo** [comment]
Awesome, thanks :)

**Comment by thomaswilburn** [comment]
No problem, just sorry it took so long!

**Pull request merged**
