### PR TITLE
Change app close button.

### PR DESCRIPTION
**Pull request by williamboman**
Tested on
- `OS X 10.10.2` `Chrome 41.0.2272.76`
- `Samsung Chromebook 2` `Chrome 40.0.2214.115`

#265

### CODE REVIEW

**Comment by thomaswilburn** [comment]
I'll have to test on Windows. Historically, it hasn't lined up well with the other two there, but maybe this is different.

**Comment by williamboman** [comment]
`OS X 10.10.2` `Chrome 41.0.2272.76`

screenshot 2015-03-07 at 21 27 58

`Samsung Chromebook 2` `Chrome 40.0.2214.115`

screenshot 2015-03-07 at 21 29 50

`Windows 7` `Version 40.0.2214.115 m`

**Comment by thomaswilburn** [comment]
Honestly, man, I appreciate the effort but I've got to think about it. I've kind of grown fond of that tilde, so I'm finding it harder than I thought I would to change it. I am sorry that it bugs you, though.

**Comment by TheThirdOne** [comment]
Same here, I have grown fond of the tilde.

**Comment by williamboman** [comment]
>Honestly, man, I appreciate the effort but I've got to think about it. I've kind of grown fond of that tilde, so I'm finding it harder than I thought I would to change it.

Understandably! It makes the app more unique :). I guess I'm more conventional.

>I am sorry that it bugs you, though.

I'm sure I'll too grow fond of it the more I use the app (downloaded it today, the tilde confused the hell out of me initially :smile:).

**Pull request closed without merging**
