### PR TITLE
Create italian messages.json

### PR DESCRIPTION
**Pull request by mattiacalicchia**
Caret italian translation!

### CODE REVIEW

**Comment by thomaswilburn** [comment]
Looks good, thanks!

**Comment by mattiacalicchia** [comment]
Thank you @thomaswilburn ! Caret is fantastic on Chrome OS 👍

**Comment by thomaswilburn** [comment]
I'll try to push out an update this weekend.

**Comment by mattiacalicchia** [comment]
Hi @thomaswilburn ! Thanks for your update, but i can see languages settings in Caret.
Where i can configure the language?
Thanks

**Comment by thomaswilburn** [comment]
Ah, I didn't notice that you created your messages file in the root. It has to be created in a folder named `it` for the localization to recognize that it's an Italian translation. I'll move it and push out a new release.

**Comment by mattiacalicchia** [comment]
Ops, i'm really sorry!
Now it works! thank you very much @thomaswilburn !
I love Caret!
I will write soon a post on my social and on my website
Have a nice day
If you need help for Italian translation write me on github ;)

**Pull request merged**
