### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by ishutinov**
Add extensions array for fast edit files in Chrome OS Files application. This extensions array add next option: Select file in Files -> press mouse right -> select in menu "Open with Caret"

### CODE REVIEW

**Comment by thomaswilburn** [comment]
How did you pick these extensions? There was a grunt task that would copy extensions into the file, but it causes problems when it goes over 255 items.

**Comment by ishutinov** [comment]
https://developer.chrome.com/apps/manifest/file_handlers

**Comment by thomaswilburn** [comment]
No, I understand _where_ you got the idea of adding extensions. I'm asking why you picked these particular extensions. There is a build task that used to add them all to the manifest automatically, powered from the ace.json config file. I removed it, because Chrome OS doesn't like it when you specify a reasonably large number of extensions, and then people get salty if their language isn't picked for first-class treatment.

**Comment by ishutinov** [comment]
I've added the most common file extensions that developers can use. Extensions deduced from the analysis of other text-based code editors. Why did I add this? - Because I can not open the code file in Files Chrome OS via SFTP, for example with .php extension, for further editing, while competitors have this function.

**Comment by thomaswilburn** [comment]
Okay. Let me think about this over the weekend. I'm not super comfortable with this change, given as much grief as I took the last time this was a common manifest feature. I recommend using the projects view instead of Files if possible, it sidesteps the whole problem.

**Pull request closed without merging**
