### PR TITLE
New UI Enhancements for #521

### PR DESCRIPTION
**Pull request by richiksc**
**This PR includes:**
* New theme-matching menus with easier to read shortcut text
* New standard window controls with minimize, maximize, restore, and close
* New app icon
* Settings menu is now the app menu
* Updated tab design
* Change San Francisco font to `-apple-system`
* New UI icon font with JS updates for icon click listeners

Tested on all themes - looks great, and functions correctly

### CODE REVIEW

**Comment by thomaswilburn** [comment]
Thanks for the PR! I'll have some more thoughts in a bit, when I have a chance to actually try the design on Chrome OS and Windows. Looking forward to it.

I did want to comment at the start on the use of the icon font loaded over XHR. One of the advantages of Caret at the moment is that it runs entirely offline, and never requests any network access (which means the privacy policy is super simple). If you want to use an icon font, it should almost certainly be included in the package itself instead of loading from a remote server.

**Comment by richiksc** [comment]
Sorry, I didn't make it clear that I developed this on a Windows machine, and I haven't tested it on ChromeOS or OS X/macOS. I just changed "San Francisco" to `-apple-system` based off of another project I did and something I read.

As you can see, there are two icon fonts - one is Google's Material Icons loaded over XHR, and the other is a custom icon font that I designed. The Google Material Icons are there temporarily as I design all the custom icons for Caret (`caret-icons`).

**Comment by thomaswilburn** [comment]
Okay, before you get too far:

* I'm not wild about the new icon or the menu arrangement.
* The new tabs don't reflect the "unsaved changes state," so I can't tell whether a file is modified at a glance, which is important.
* I find the new menus to be lower contrast, and thus harder to read. The command line is also harder to read now. There's a reason they're always dark-on-light.
* Since all this work was done on the `project-rewrite` branch, which is currently not merged into `master`, we'd need to port most of this over before it can be used. Mostly that's not a problem, but you never know. It also means it's missing all the improvements that were make to project-wide search in 1.6.x.

I see where you're going with this, and I appreciate the effort. There are some things here that I would like to incorporate, like the increase in hover state feedback. I don't think it's probably the way I want Caret to look, though. The good news is that if it really bugs you, Caret is unlikely to go through significant architectural changes in the future, so you can probably run your own fork of it locally and just pull my changes whenever I add features that make a difference for you.

Thanks again for the work!

**Comment by richiksc** [comment]
Sorry, I don't see how the menus are lower contrast&mdash;they're foreground on the faded background, so they're light-on-dark in the dark theme and dark-on-light in the light theme.

Is there any plan to incorporate the less significant changes? Some of them are just tiny visual improvements, like how the `<select>` elements for the language and theme inherit the font family and the reversal of the drop shadow on the palette.

I never noticed missing an unsaved changes state, that is something I need to add.

What specifically about the app icon bugs you? Is it the icon as a whole, how the 'C' and the caret are different colors, or something else?

We can for sure bring the default menu arrangement back, but we should still have the app icon in the corner.

**Comment by thomaswilburn** [comment]
The background is now a mix that's closer to middle gray, and the foreground hasn't changed--that's much lower contrast, particularly in the light theme, than the old black-on-white text was. Plus light text on a dark background is tougher to read by default. We're not going to switch back to themed menus, period.

I don't have an ETA for picking up some of the smaller changes. I'll take a look at it, but it's a busy month at the paper and I have two conference talks to prepare for, so this is not really going to be a high priority for me right now.

**Pull request closed without merging**
