### PR TITLE
Brackets highlight in cobalt theme

### PR DESCRIPTION
**Pull request by rumatakira**
It is almost impossible to see matching parentheses in cobalt theme - so I changed theme-cobalt.js in ~/.config/chromium/Default/Extensions/fljalecfjciodhpcledpamjachpmelml/X.X.X_X/js/ace/theme-cobalt.js:
````js
.ace-cobalt .ace_marker-layer .ace_bracket {\
background: rgb(0, 197, 205)\
}\
````

### CODE REVIEW

**Comment by thomaswilburn** [comment]
Changes to the Ace files need to be submitted to their repo, then we'll pull from upstream. Generally, we try not to modify any Ace files if possible, it just makes it easier for me to stay up to date.

**Comment by rumatakira** [comment]
Ok. I understand you. But you create Caret for the user... ;))

**Comment by thomaswilburn** [comment]
Sure, but if you submit stuff to Ace instead of to me, then the editing gets better for ALL the users, not just the ones who download my software.

**Comment by rumatakira** [comment]
Never mind. Thomas - this is the small thing. Commonly the editor is very good. For me much better than Atom, for example. Thank you!

**Pull request closed without merging**
