### PR TITLE
Added option to completely hide project sidebar

### LINKED ISSUE #340: project sidebar request
I would like an option to **disable** the project sidebar from opening AND still have a project.

The delay _seemed_ helpful, but recently the project sidebar is popping out more when the mouse pointer strays. Maybe it is simply that I am using Caret more and more and more. Caret is great... thank you.

I prefer to use `Tools > Go To...` to open files that I know are in the project.
Not only would the project sidebar **not get in the way**, but the `Tools > Go To...` is so much **faster**!
If I need access to files I do not remember in the project, I can use the Chromebook `File.app`.

### PR DESCRIPTION
**Pull request by grit96**
Fixes #340

### CODE REVIEW

**Comment by thomaswilburn** [comment]
This seems more complicated than it need to be. Instead of creating a new class, why not just return early from ProjectManager.render(), before adding the "show" class? We already do so if it's empty, after all.

**Comment by grit96** [comment]
This doesn't work when you change the setting without restarting Caret, it will just stay hidden until you restart. Setting the classes handles that situation.

**Comment by thomaswilburn** [comment]
That's a fair point, but you could still just remove "show" instead of adding a new class, and it would simplify the code quite a bit.

**Comment by grit96** [comment]
Removed the hidden class and it's now a little simpler.

**Comment by thomaswilburn** [comment]
I know, I'm just harping on things now, but: I don't think we should ever add the "show" class here, only remove it. Adding the class should be something that we only do in render(). Otherwise, you're going to end up with an empty project panel displayed if autoHide is turned on.

**Comment by thomaswilburn** [comment]
Actually, tell you what: I don't want to waste your time, and the project manager is currently under work in the `project-rewrite` branch, which is going to wipe out this code anyway. Why don't we table this for now, and come back to it if I don't address it in that branch?

**Comment by grit96** [comment]
OK thanks

**Pull request closed without merging**
